// AUTO-GENERATED by scripts/build-japanese-data.mjs. Do not edit manually.
const JAPANESE_TOPICS = [
  {
    "id": "01",
    "type": "quiz",
    "title": {
      "vi": "Kiến thức Nhật Bản – Có duyên",
      "ja": "日本クイズ・ご縁"
    },
    "description": {
      "vi": "Kiến thức tổng hợp về đời sống, xã hội và văn hóa Nhật Bản.",
      "ja": "日本の生活・社会・文化に関する総合問題。"
    },
    "count": 328,
    "source": "01_NhatBan_quiz_CO_DUYEN.md"
  },
  {
    "id": "02",
    "type": "quiz",
    "title": {
      "vi": "Địa lý Nhật Bản",
      "ja": "日本の地理"
    },
    "description": {
      "vi": "Địa danh, vùng miền, khí hậu và đặc điểm tự nhiên.",
      "ja": "地域、気候、自然など日本地理の問題。"
    },
    "count": 48,
    "source": "02_Dia_ly_Nhat_Ban.md"
  },
  {
    "id": "03",
    "type": "quiz",
    "title": {
      "vi": "Thể thao và âm nhạc",
      "ja": "スポーツと音楽"
    },
    "description": {
      "vi": "Các sự kiện, nhân vật và kiến thức thể thao, âm nhạc.",
      "ja": "スポーツと音楽の出来事や人物に関する問題。"
    },
    "count": 25,
    "source": "03_The_thao_va_am_nhac.md"
  },
  {
    "id": "04",
    "type": "quiz",
    "title": {
      "vi": "Quiz Nhật Bản – Cấp độ 1",
      "ja": "日本クイズ・レベル1"
    },
    "description": {
      "vi": "Bộ câu hỏi nền tảng dành cho người mới bắt đầu.",
      "ja": "初級者向けの基礎問題。"
    },
    "count": 200,
    "source": "04_Quiz_Nhat_Ban_cap_do_1.md"
  },
  {
    "id": "05",
    "type": "quiz",
    "title": {
      "vi": "Quiz Nhật Bản – Cấp độ 2",
      "ja": "日本クイズ・レベル2"
    },
    "description": {
      "vi": "Bộ câu hỏi mở rộng ở mức độ trung cấp.",
      "ja": "中級レベルの発展問題。"
    },
    "count": 260,
    "source": "05_Quiz_Nhat_Ban_cap_do_2.md"
  },
  {
    "id": "06",
    "type": "quiz",
    "title": {
      "vi": "Quiz Nhật Bản – Cấp độ 3",
      "ja": "日本クイズ・レベル3"
    },
    "description": {
      "vi": "Bộ câu hỏi nâng cao về Nhật Bản.",
      "ja": "日本に関する上級問題。"
    },
    "count": 240,
    "source": "06_Quiz_Nhat_Ban_cap_do_3.md"
  },
  {
    "id": "07",
    "type": "quiz",
    "title": {
      "vi": "Quan – Hôn – Tang – Tế",
      "ja": "冠婚葬祭"
    },
    "description": {
      "vi": "Phong tục và nghi lễ quan trọng trong đời sống người Nhật.",
      "ja": "日本の人生儀礼や慣習に関する問題。"
    },
    "count": 40,
    "source": "07_Quan_hon_tang_te.md"
  },
  {
    "id": "08",
    "type": "quiz",
    "title": {
      "vi": "Sự kiện trong năm",
      "ja": "年中行事"
    },
    "description": {
      "vi": "Ngày lễ và các sự kiện truyền thống diễn ra trong năm.",
      "ja": "日本の祝日や伝統的な年中行事。"
    },
    "count": 51,
    "source": "08_Su_kien_trong_nam.md"
  },
  {
    "id": "09",
    "type": "material",
    "title": {
      "vi": "Văn hóa, lịch sử và tư duy Nhật Bản",
      "ja": "日本の文化・歴史・思想"
    },
    "description": {
      "vi": "Tài liệu đọc về sự hình thành văn hóa và tư duy của người Nhật.",
      "ja": "日本人の文化、歴史、考え方を学ぶ読み物。"
    },
    "href": "./materials/09.html",
    "source": "09_Van_hoa_lich_su_va_tu_duy_Nhat_Ban.md"
  },
  {
    "id": "10",
    "type": "material",
    "title": {
      "vi": "Văn học Nhật Bản",
      "ja": "日本文学"
    },
    "description": {
      "vi": "Tổng quan các tác phẩm, tác giả và giai đoạn văn học Nhật Bản.",
      "ja": "日本文学の作品、作家、時代を学ぶ読み物。"
    },
    "href": "./materials/10.html",
    "source": "10_Van_hoc_Nhat_Ban.md"
  }
];
